"""
A decorator with syntax to inject keyword arguments into decorated callables
when they are called. The values of the keyword arguments are either literals
or generated by factory functions. The factory receives arguments provided in
the decorator as well as passed to the call.

TODO - example
"""

# TODO - disable all static type check ignores and document exactly when and
#        why they occur, what would be needed to add proper types. The concern
#        with an untypable library is it encourages global or module type
#        ignores which can then hide other ignores. Understanding exactly why
#        they happen is important to know what features need to be added to
#        typing or checkers or extensions, provide guidance to users on how to
#        know one that they see is a limitation in the library/typing rather
#        than an issue they should try to solve, and ensure there aren't proper
#        fixes. Perhaps @overloads or cover methods, etc can mitigate the urge
#        to add global/module ignores.
# todo? - if callable is not a _Decorator.__call__.wrapper inspect the
#         signature and only pass requested arguments if it doesn't take
#         arbitrary argss. This will remove need for **_ on decorated functions
#         that don't want all of the intermediate kwargs.
# todo? - deep call stacks since the decorators wrap, consider making stacked
#         decorators append to a list on the initial to avoid deep call stacks.
from collections.abc import Iterable, Generator
from contextlib import AbstractContextManager, contextmanager
from dataclasses import dataclass
from functools import wraps
import inspect
import traceback
from typing import Any, Callable, overload, ContextManager, ClassVar

__all__ = ("kwargs",)

type DecoratorRHS[**P, R] = _Kwarg | _PartialFactory[P, R] | object
"""
DecoratorRHS is the type that creates keyword argument values when decorated
functions are called.
"""


@dataclass
class _PartialFactory[**P, R]:
    factory: _Kwargs.factory[P, R]
    args: tuple[object, ...]
    kwargs: dict[str, object]

    @property
    def required_parameters(self) -> Iterable[inspect.Parameter]:
        """
        The parameters that must be provided by the caller.
        This includes only the factory function parameters that are not
        provided by the partial kwargs.
        """
        signature = inspect.signature(self.factory.factory)
        for parameter in signature.parameters.values():
            if (
                parameter.kind != inspect.Parameter.VAR_KEYWORD
                and parameter.name not in self.kwargs
            ):
                yield parameter

    def __call__(self, *args: object, **kwargs: object) -> R:
        """create the value for the kwarg"""
        # replace all _Kwarg values in self.kwargs with values from kwargs.
        actual_kwargs = {
            k: kwargs[v.name] if isinstance(v, _Kwarg) else v
            for k, v in self.kwargs.items()
        }
        # Do not pass args to the factory, it may contain self, is intended for
        # the decorated function. kwargs must be passed to allow get kwargs
        # from stacked decorators.
        return self.factory.factory(*self.args, **actual_kwargs, **kwargs)  # type: ignore[arg-type]


@dataclass
class _Wrapper[**P, R, **Prhs, Rrhs]:
    """
    Callable wrapper around the decorated function (or other _Wrapper).
    Exists to enable wrappers to do isinstance() on callable to determine
    if it is another wrapper.
    """

    decorator: _Decorator[Prhs, Rrhs]
    func: Callable[P, R]

    def __call__(self, *args: P.args, **kwargs: P.kwargs) -> R:
        """
        Decorated function is being called, resolve values.
        """
        match self.decorator.rhs:
            case _PartialFactory():
                # call the partial factory with the call args
                value = self.decorator.rhs(*args, **kwargs)
            case _Kwarg():
                # lookup the kwarg
                value = kwargs[self.decorator.rhs.name]
            case _:
                # use the value as a literal
                value = self.decorator.rhs

        context_manager: AbstractContextManager[R] | None = None
        if isinstance(value, AbstractContextManager):
            context_manager = value
            value = context_manager.__enter__()

        # Call the decorated function with the updated kwargs.
        kwargs[self.decorator.kwarg.name] = value

        ret: R | None = None
        try:
            ret = self.func(*args, **kwargs)
        except Exception as exc:
            if context_manager:
                if not context_manager.__exit__(
                    type(exc), exc, exc.__traceback__
                ):
                    raise
            else:
                raise
        else:
            if context_manager:
                context_manager.__exit__(None, None, None)

        # Interesting conundrum...if the function raised but a fixture context
        # manager suppresses the exception exactly what should the return value
        # be? I'm not exactly sure, so...
        return ret  # type: ignore # todo semantics of error suppression


@dataclass
class _Decorator[**Prhs, Rrhs]:
    """
    Decorator that creates and injects a kwarg into an wrapped callable.
    **Prhs, Rrhs are for the right hand side.
    """

    kwarg: _Kwarg
    rhs: DecoratorRHS[Prhs, Rrhs]

    # __call__ should be -> Callable[[P.kwargs - {self.kwarg: Rrhs}], R] to
    # indicate the kwarg is being injected (and the wrapper does not need it
    # passed in), but that is not supported. Typing is best effort, but
    # decorated functions will appear to require args/kwargs that they don't.
    def __call__[**P, R](self, func: Callable[P, R]) -> Callable[P, R]:
        """
        Decorator is being applied, return the wrapper around the callable.
        """
        # The wrapper can not be used directly because it won't invoke the
        # bound method handling and self won't be injected if the decorated
        # function is a method. Return a function that dispatches to the
        # wrapper when called.
        # todo? annotate the function with the wrapper?
        wrapper = _Wrapper(self, func)

        @self._set_signature
        @wraps(func)
        def _wrapper(*args: P.args, **kwargs: P.kwargs) -> R:
            return wrapper(*args, **kwargs)

        return _wrapper

    def _set_signature[**P, R](
        self, wrapper: Callable[P, R]
    ) -> Callable[P, R]:
        """
        Private decorator to put a __signature__ on the wrapper to reflect
        reality (at runtime anyway).

        The injected argument is removed from the signature parameters since
        the wrapper adds it when calling the decorated function.
        Fixture function parameters that aren't already in the parameter list
        are added. This is so pytest will see that they are needed for the
        call to the decorated function and satisfy them (hopefully) with pytest
        fixtures.
        This function exists primarily to allow interoperation with pytest
        fixtures.
        """
        signature = inspect.signature(wrapper)

        # Remove the injected argument from the parameters.
        parameters = [
            param
            for name, param in signature.parameters.items()
            if name != self.kwarg.name
        ]

        # Add any parameters the fixture func has that don't already exist.
        # todo? adding the factory args to the signature is technically
        # correct, they must be passed in to the wrapper for the
        # factory to execute. However this introduces the problem that
        # they are passed through to the decorated function which may
        # not know anything about them...they are an implementation
        # detail of the kwargs decorator stack that currently leaks
        # into the decorated function as an unexpected # kwarg that
        # needs to be accepted (**_). This could be managed by tracking
        # that this parameter was added for this reason and removing it
        # from kwargs once it has been used by the factory, but not
        # today.
        if isinstance(self.rhs, _PartialFactory):
            with _out_var_keyword(parameters) as parameters:
                for param in self.rhs.required_parameters:
                    if not any(
                        _param.name == param.name for _param in parameters
                    ):
                        parameters.append(param)

        # Set the modified signature on the wrapper.
        signature = signature.replace(parameters=parameters)
        setattr(wrapper, "__signature__", signature)
        return wrapper


@contextmanager
def _out_var_keyword(
    parameters: list[inspect.Parameter],
) -> Generator[list[inspect.Parameter]]:
    """
    Context manager to remove the last VAR_KEYWORD parameter and add it back.

    Usage:
        parameters = inspect.signature(func).parameters.values()
        with out_var_keyword(parameters) as parameters:
            ...
            parameters.append(...)

    """
    var_keyword_param: inspect.Parameter | None = None
    if parameters and parameters[-1].kind == inspect.Parameter.VAR_KEYWORD:
        var_keyword_param = parameters[-1]
        parameters = parameters[:-1]

    yield parameters

    if var_keyword_param:
        parameters.append(var_keyword_param)


@dataclass
class _Kwarg:
    """
    _Kwarg is a reference to a kwarg.
    It is basically a name with a bit of functionality:
        - marker to replace a kwarg with another kwarg when executing the
          decorator stack.
        - functionality to create a decorator that will inject a kwarg:
          _Kwarg(...) << ...

    Pipe dream: if __setitem__() was allowed to return a value, and the
    'cannot assign to subscript here' error was removed when trying to assign
    a subscript in a decorator, this class could implement __setitem__() rather
    than __lshift__() and the decorator could be spelled '@ kwarg['foo'] = 1'.
    """

    name: str
    """the name of the kwarg"""

    def __call__(self, *args: Any, **kwargs: Any) -> None:
        raise TypeError(
            "incomplete Kwarg can not be used as decorator, "
            "complete it by providing a value using "
            "'@kwarg['kwarg'] << ...'"
        )

    @overload
    def __lshift__[**Prhs, Rrhs](
        self, factory: _Kwarg
    ) -> _Decorator[Prhs, object]: ...

    @overload
    def __lshift__[**Prhs, Rrhs](
        self, factory: _PartialFactory[Prhs, Rrhs]
    ) -> _Decorator[Prhs, Rrhs]: ...

    @overload
    def __lshift__[**Prhs, Rrhs](
        self, factory: Rrhs
    ) -> _Decorator[Prhs, Rrhs]: ...

    def __lshift__[**Prhs, Rrhs](
        self, factory: DecoratorRHS[Prhs, Rrhs]
    ) -> _Decorator[Prhs, Rrhs]:
        return _Decorator(self, factory)


class _Kwargs:
    """
    Interface for kwarg injection.

    kwargs.factory - decorator to create a partial for a callable that can
                      be used to create keyword argument values to be injected
                      at call time.
    """

    @dataclass
    class factory[**P, R]:
        """
        Decorator that marks a callable as a kwarg value factory.

        Applying @kwargs.factory to a function allows it to be used on the
        right-hand side of a kwarg injection decorator (kwargs[...] << ...).
        When called with arguments, it returns a partial factory whose
        remaining arguments are supplied at the time the decorated function is
        called.
        TODO - example
        """

        # TODO - this is really ugly:
        #    1) The datamodel must use non-factories for references between classes, so
        #       the classes can't themselves be decorated with @kwargs.factory.
        #    2) kwargs decorators must use factories
        #         it could be spelled:
        #            @ kwargs["origin"] << kwargs.factory(Point)(0, 0)
        #         but that seems worse and creates massive bloat unless they are
        #         interned.
        #    3) the factory looks like a Point, but isn't a point, so the decorated
        #       function will be typed differently:
        #       @ kwargs['origim'] << Point(1, 1)
        #       def test_origin(origin: model.Point): ...
        #
        #  In practice, how ugly is it, really? The models are likely to already be
        #  defined elsewhere (in the code being tested) so:
        #      Point = kwargs.factory(model.Point)
        #  would likely be the 'proper' way to do it, which is alright(?).
        #
        #  This wasn't an issue with original @fixture(...) because it didn't create
        #  partial factories, it just held the factory and kwargs.
        #    1) the partial factory is 'needed' to disambiguate factory from kwarg
        #       from literal. It could assume any callable is a factory, but that is
        #       implicit (and explicit is better).
        #    2) the '<<< Point(1)' syntax is more readable (IMO) than '(Point, 1)'.
        #
        #  If the factories explicitly supported currying by creating a curried object
        #  that was detectable in the same way _FactoryPartial is this could be
        #  improved, but I don't want to require datamodels be extended from things
        #  that are just for test code. The test code shouldn't be in production and
        #  testing with it and shipping without is a Bad Idea.
        #
        #  So, what to do?
        #    1) different syntax rather than isinstance?
        #        @ kwargs['foo'] == literal_value # or kwargs['bar']
        #        @ kwargs['foo'] << (Point, 1)
        #    2) ???
        #
        #  For now, targets must be factories...Yuck.

        factory: Callable[P, R]

        def __call__(
            self, *args: object, **kwargs: object
        ) -> _PartialFactory[P, R]:
            return _PartialFactory(self, args, kwargs)

    @staticmethod
    def __getitem__(name: str) -> _Kwarg:
        """
        Create a _Kwarg with the given name.
        Used to create a keyword argument injection decorator:
            @ kwargs['argument_name'] << ...
        Or to indicate a factory function argument should be retrieved from
        the kwargs of the call:
            @ ... << factory(foo=kwargs['bar'])
        """
        return _Kwarg(name)  # todo? - intern this?


# Class subscription is restricted to generic types, use an instance. It is
# trivial to use __class_getitem__ and it works, but static type checkers don't
# like it, for good reason, and using it in this way is discouraged by the
# docs, so, just use an instance instead.
kwargs = _Kwargs()
