"""
A decorator with syntax to inject keyword arguments into decorated callables
when they are called. The values of the keyword arguments are either literals
or generated by factory functions. The factory receives arguments provided in
the decorator as well as passed to the call.

TODO - example
"""

# todo? - if callable is not a _Decorator.__call__.wrapper inspect the
#         signature and only pass requested arguments if it doesn't take
#         arbitrary argss. This will remove need for **_ on decorated functions
#         that don't want all of the intermediate kwargs.

from typing import Any, Callable, overload
from dataclasses import dataclass
from functools import wraps

__all__ = ("kwargs",)


type DecoratorRHS[**P, R] = _Kwarg | _PartialFactory[P, R] | object
"""
DecoratorRHS is the type that creates keyword argument values when decorated
functions are called.
"""


@dataclass
class _PartialFactory[**P, R]:
    factory: _Kwargs.factory[P, R]
    args: tuple[object, ...]
    kwargs: dict[str, object]

    def __call__(self, *args: object, **kwargs: object) -> R:
        """create the value for the kwarg"""
        # replace all _Kwarg values in self.kwargs with values from kwargs.
        actual_kwargs = {
            k: kwargs[v.name] if isinstance(v, _Kwarg) else v
            for k, v in self.kwargs.items()
        }
        return self.factory.factory(
            *self.args, *args, **actual_kwargs, **kwargs  # type: ignore[arg-type]  # todo
        )


@dataclass
class _Decorator[**P, R, **Prhs, Rrhs]:
    """
    Decorator that creates and injects a kwarg into an wrapped callable.
    **P, R are the ParamSpec and return type for the decorated function.
    **Prhs, Rrhs are for the right hand side.
    """

    kwarg: _Kwarg
    rhs: DecoratorRHS[Prhs, Rrhs]

    # __call__ should be -> Callable[[P.kwargs - {self.kwarg: Rrhs}], R] to
    # indicate the kwarg is being injected (and the wrapper does not need it
    # passed in), but that is not supported. Typing is best effort, but
    # decorated functions will appear to require args/kwargs that they don't.
    def __call__(self, func: Callable[P, R]) -> Callable[P, R]:
        """
        Decorator is being applied, return the wrapper around the callable.
        """

        @wraps(func)
        def wrapper(*args: P.args, **kwargs: P.kwargs) -> R:
            """
            Decorated function is being called, resolve values.
            """
            match self.rhs:
                case _PartialFactory():
                    # call the partial factory with the call args
                    value = self.rhs(*args, **kwargs)
                case _Kwarg():
                    # lookup the kwarg
                    value = kwargs[self.rhs.name]
                case _:
                    # use the value as a literal
                    value = self.rhs

            # Call the decorated function with the updated kwargs.
            kwargs[self.kwarg.name] = value
            return func(*args, **kwargs)

        return wrapper


@dataclass
class _Kwarg:
    """
    _Kwarg is a reference to a kwarg.
    It is basically a name with a bit of functionality:
        - marker to replace a kwarg with another kwarg when executing the
          decorator stack.
        - functionality to create a decorator that will inject a kwarg:
          _Kwarg(...) << ...

    Pipe dream: if __setitem__() was allowed to return a value, and the
    'cannot assign to subscript here' error was removed when trying to assign
    a subscript in a decorator, this class could implement __setitem__() rather
    than __lshift__() and the decorator could be spelled '@ kwarg['foo'] = 1'.
    """

    name: str
    """the name of the kwarg"""

    def __call__(self, *args: Any, **kwargs: Any) -> None:
        raise TypeError(
            "incomplete Kwarg can not be used as decorator, "
            "complete it by providing a value using "
            "'@kwarg['kwarg'] << ...'"
        )

    @overload
    def __lshift__[**P, R, **Prhs, Rrhs](
        self, factory: _Kwarg
    ) -> _Decorator[P, R, Prhs, Rrhs]: ...

    @overload
    def __lshift__[**P, R, **Prhs, Rrhs](
        self, factory: _PartialFactory[Prhs, Rrhs]
    ) -> _Decorator[P, R, Prhs, Rrhs]: ...

    @overload
    def __lshift__[**P, R, **Prhs, Rrhs](
        self, factory: R
    ) -> _Decorator[P, R, Prhs, Rrhs]: ...

    def __lshift__[**P, R, **Prhs, Rrhs](
        self, rhs: DecoratorRHS[P, R]
    ) -> _Decorator[P, R, Prhs, Rrhs]:
        return _Decorator(self, rhs)


class _Kwargs:
    """
    Interface for kwarg injection.

    kwargs.factory - decorator to create a partial for a callable that can
                      be used to create keyword argument values to be injected
                      at call time.
    """

    @dataclass
    class factory[**P, R]:
        """
        Decorator that marks a callable as a kwarg value factory.

        Applying @kwargs.factory to a function allows it to be used on the
        right-hand side of a kwarg injection decorator (kwargs[...] << ...).
        When called with arguments, it returns a partial factory whose
        remaining arguments are supplied at the time the decorated function is
        called.
        TODO - example
        """

        factory: Callable[P, R]

        def __call__(
            self, *args: object, **kwargs: object
        ) -> _PartialFactory[P, R]:
            return _PartialFactory(self, args, kwargs)

    @staticmethod
    def __getitem__(name: str) -> _Kwarg:
        """
        Create a _Kwarg with the given name.
        Used to create a keyword argument injection decorator:
            @ kwargs['argument_name'] << ...
        Or to indicate a factory function argument should be retrieved from
        the kwargs of the call:
            @ ... << factory(foo=kwargs['bar'])
        """
        return _Kwarg(name)  # todo? - intern this?


# Class subscription is restricted to generic types, use an instance. It is
# trivial to use __class_getitem__ and it works, but static type checkers don't
# like it, for good reason, and using it in this way is discouraged by the
# docs, so, just use an instance instead.
kwargs = _Kwargs()
